// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABuEVrwPbKRESMUsINBBOGuEHZzrjBR-0',
    appId: '1:840885865156:web:b68f3cf30546cda3965791',
    messagingSenderId: '840885865156',
    projectId: 'notas-86899',
    authDomain: 'notas-86899.firebaseapp.com',
    storageBucket: 'notas-86899.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoD1-kfmO2sfWe4h8PkC1_-POi_9lK9C8',
    appId: '1:840885865156:android:040638c83a20e886965791',
    messagingSenderId: '840885865156',
    projectId: 'notas-86899',
    storageBucket: 'notas-86899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQleD3qJgqwCFWDBb0U5dJPGB3WIR1uzw',
    appId: '1:840885865156:ios:b5ed5d309b44429b965791',
    messagingSenderId: '840885865156',
    projectId: 'notas-86899',
    storageBucket: 'notas-86899.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQleD3qJgqwCFWDBb0U5dJPGB3WIR1uzw',
    appId: '1:840885865156:ios:b9b3a134be692001965791',
    messagingSenderId: '840885865156',
    projectId: 'notas-86899',
    storageBucket: 'notas-86899.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
