// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8RLLxQkbpQ2qJY_9091iLl-hC-XZqNi8',
    appId: '1:644962621106:web:100becede7d694fd255bab',
    messagingSenderId: '644962621106',
    projectId: 'users-4a5f7',
    authDomain: 'users-4a5f7.firebaseapp.com',
    storageBucket: 'users-4a5f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC58VbR9eqH6P3CW5poHuNKCvRvjXG02qo',
    appId: '1:644962621106:android:97883bccfe71e317255bab',
    messagingSenderId: '644962621106',
    projectId: 'users-4a5f7',
    storageBucket: 'users-4a5f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuyUZD679ppMAZOeJoA2NyNUZ5eigPSK0',
    appId: '1:644962621106:ios:7b5349a817c02000255bab',
    messagingSenderId: '644962621106',
    projectId: 'users-4a5f7',
    storageBucket: 'users-4a5f7.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuyUZD679ppMAZOeJoA2NyNUZ5eigPSK0',
    appId: '1:644962621106:ios:c042782aa7f1ee29255bab',
    messagingSenderId: '644962621106',
    projectId: 'users-4a5f7',
    storageBucket: 'users-4a5f7.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
